# Nama : Nurmedina Maulidiah    
# NIM  : 2109106012
## Posttest 7 Kecerdasan Buatan (Pengenalan Tensor)

## Import Libary

In [6]:
import tensorflow as tf

# Membuat Tensor

## Membuat Tensor dengan variable random_tensor dengan shape [5,5]

In [7]:
random_tensor = tf.random.normal([5,5])
random_tensor.numpy()

array([[ 0.560855  , -0.687526  , -0.10960045,  0.7286616 ,  0.94300914],
       [-0.6480309 , -0.97411764, -0.49935198, -0.91106695, -0.8070118 ],
       [ 1.6458039 ,  0.13402535,  0.9267063 ,  1.5693231 ,  0.8819627 ],
       [-0.79383236,  1.6901172 , -0.0040522 , -0.47295114,  0.2412777 ],
       [-1.8602692 , -0.8628474 , -1.2628676 , -0.10913838,  0.8408096 ]],
      dtype=float32)

## Membuat Tensor dengan variable prime_tensor dengan shape [5,5]

In [8]:
prime_tensor = tf.constant([2,3,5,7,11,13,17,19,23,29, 31, 37, 41, 43, 47, 53, 59, 61, 71, 73, 79, 83, 89, 97, 101], shape=[5,5], dtype=tf.float32)
prime_tensor.numpy()

array([[  2.,   3.,   5.,   7.,  11.],
       [ 13.,  17.,  19.,  23.,  29.],
       [ 31.,  37.,  41.,  43.,  47.],
       [ 53.,  59.,  61.,  71.,  73.],
       [ 79.,  83.,  89.,  97., 101.]], dtype=float32)

# Menampilkan dimensi dari kedua variable tersebut

In [9]:
dim_display = tf.constant(['random_tensor'], shape=[5,5])
dim_display.shape

TensorShape([5, 5])

In [10]:
dim_display.get_shape()

TensorShape([5, 5])

In [11]:
dim_display1 = tf.constant(['prime_tensor'], shape=[5,5])
dim_display1.shape

TensorShape([5, 5])

In [12]:
dim_display1.get_shape()

TensorShape([5, 5])

# Operasi Aritmtika dari variable random_tensor dan variable

## Penjumlahan

In [13]:
add = random_tensor + prime_tensor
add.numpy()

array([[  2.560855 ,   2.312474 ,   4.8903995,   7.7286615,  11.943009 ],
       [ 12.351969 ,  16.025883 ,  18.500648 ,  22.088934 ,  28.192987 ],
       [ 32.645805 ,  37.134026 ,  41.926704 ,  44.569324 ,  47.88196  ],
       [ 52.20617  ,  60.690117 ,  60.99595  ,  70.52705  ,  73.24128  ],
       [ 77.13973  ,  82.13715  ,  87.73713  ,  96.89086  , 101.84081  ]],
      dtype=float32)

## Pengurangan

In [14]:
add = random_tensor - prime_tensor
add.numpy()

array([[  -1.4391451,   -3.687526 ,   -5.1096005,   -6.2713385,
         -10.056991 ],
       [ -13.648031 ,  -17.974117 ,  -19.499352 ,  -23.911066 ,
         -29.807013 ],
       [ -29.354197 ,  -36.865974 ,  -40.073296 ,  -41.430676 ,
         -46.11804  ],
       [ -53.79383  ,  -57.309883 ,  -61.00405  ,  -71.47295  ,
         -72.75872  ],
       [ -80.86027  ,  -83.86285  ,  -90.26287  ,  -97.10914  ,
        -100.15919  ]], dtype=float32)

## Perkalian

In [32]:
add = random_tensor * prime_tensor
add.numpy()

array([[  1.51127   ,   9.077652  ,   4.0895934 ,   1.7468362 ,
        -11.548924  ],
       [ -3.703165  ,  -8.9441595 , -17.545458  , -12.842205  ,
        -14.309954  ],
       [ 74.63964   ,  80.89042   ,   7.959754  ,  69.018105  ,
         24.572147  ],
       [-10.2628    , -32.466297  ,  52.31611   , -81.495964  ,
        -18.67848   ],
       [  1.3819202 ,  -0.47728068, 113.84883   , -90.767235  ,
        -71.610054  ]], dtype=float32)

## Pembagian

In [35]:
add = random_tensor / prime_tensor
add.numpy()

array([[ 3.7781751e-01,  1.0086280e+00,  1.6358374e-01,  3.5649717e-02,
        -9.5445655e-02],
       [-2.1912219e-02, -3.0948650e-02, -4.8602376e-02, -2.4276381e-02,
        -1.7015403e-02],
       [ 7.7668719e-02,  5.9087232e-02,  4.7351304e-03,  3.7327264e-02,
         1.1123653e-02],
       [-3.6535424e-03, -9.3267160e-03,  1.4059690e-02, -1.6166627e-02,
        -3.5050630e-03],
       [ 2.2142609e-04, -6.9281567e-05,  1.4373037e-02, -9.6468525e-03,
        -7.0199054e-03]], dtype=float32)

## Pangkat dua

In [36]:
add = random_tensor ** prime_tensor
add.numpy()

array([[ 5.7098430e-01,  2.7704912e+01,  3.6605871e-01,  6.0266902e-05,
        -1.7085878e+00],
       [-8.1317943e-08, -1.8135961e-05, -2.2019686e-01, -1.5099791e-06,
        -1.2704765e-09],
       [ 6.7583895e+11,  3.7044906e+12,  6.4975204e-30,  6.8591027e+08,
         5.7839841e-14],
       [-1.6235688e-38, -4.9461123e-16,  8.5435961e-05, -1.7836951e+04,
        -0.0000000e+00],
       [ 0.0000000e+00, -0.0000000e+00,  3.2925445e+09, -1.5931828e-03,
        -8.2397597e-16]], dtype=float32)

# Menampilkan nilai maksimum dan minimum dari variable random_tensor

In [31]:
max = tf.argmax(random_tensor, axis=0)
max

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([2, 0, 4, 2, 2], dtype=int64)>

In [19]:
min = tf.argmin(random_tensor, axis=0)
min

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([4, 0, 4, 3, 2], dtype=int64)>

# Menampilkan hasil dari penggabungan variable random_tensor dengan prime_tensor (concatenation)

In [16]:
random_prime = tf.concat([random_tensor, prime_tensor], axis =0)
random_prime.numpy()

array([[ 5.60854971e-01, -6.87525988e-01, -1.09600447e-01,
         7.28661597e-01,  9.43009138e-01],
       [-6.48030877e-01, -9.74117637e-01, -4.99351978e-01,
        -9.11066949e-01, -8.07011783e-01],
       [ 1.64580393e+00,  1.34025350e-01,  9.26706314e-01,
         1.56932306e+00,  8.81962717e-01],
       [-7.93832362e-01,  1.69011724e+00, -4.05220082e-03,
        -4.72951144e-01,  2.41277695e-01],
       [-1.86026919e+00, -8.62847388e-01, -1.26286757e+00,
        -1.09138384e-01,  8.40809584e-01],
       [ 2.00000000e+00,  3.00000000e+00,  5.00000000e+00,
         7.00000000e+00,  1.10000000e+01],
       [ 1.30000000e+01,  1.70000000e+01,  1.90000000e+01,
         2.30000000e+01,  2.90000000e+01],
       [ 3.10000000e+01,  3.70000000e+01,  4.10000000e+01,
         4.30000000e+01,  4.70000000e+01],
       [ 5.30000000e+01,  5.90000000e+01,  6.10000000e+01,
         7.10000000e+01,  7.30000000e+01],
       [ 7.90000000e+01,  8.30000000e+01,  8.90000000e+01,
         9.70000000e+01

# Tampilkan hasil sorting dari kedua variable di atas (descending)

## Sorting Variable random_tensor

In [17]:
tf_sort = tf.sort(random_tensor, direction="DESCENDING")
tf_sort.numpy()

array([[ 0.94300914,  0.7286616 ,  0.560855  , -0.10960045, -0.687526  ],
       [-0.49935198, -0.6480309 , -0.8070118 , -0.91106695, -0.97411764],
       [ 1.6458039 ,  1.5693231 ,  0.9267063 ,  0.8819627 ,  0.13402535],
       [ 1.6901172 ,  0.2412777 , -0.0040522 , -0.47295114, -0.79383236],
       [ 0.8408096 , -0.10913838, -0.8628474 , -1.2628676 , -1.8602692 ]],
      dtype=float32)

In [18]:
tf_sort = tf.sort(prime_tensor, direction="DESCENDING")
tf_sort.numpy()

array([[ 11.,   7.,   5.,   3.,   2.],
       [ 29.,  23.,  19.,  17.,  13.],
       [ 47.,  43.,  41.,  37.,  31.],
       [ 73.,  71.,  61.,  59.,  53.],
       [101.,  97.,  89.,  83.,  79.]], dtype=float32)